# Spring properties
spring:
  application:
    name: restaurant-service  # Service registers under this name
  messages:
    fallback-to-system-locale: false
  cloud :
    config :
      uri : http://localhost:8088
      fail-fast : false
      label : master
  profiles : docker
  
app:
  greet:
    msg : Hello Microservice
    
management:
  endpoints:
    web:
      exposure:
        include: "refresh"
   
  
 #Discoveryu Server Access
eureka:
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 2
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/  
    fetch-registry: true
    
# HTTP Server
server:
  port: 2224   # HTTP (Tomcat) port
  
---
# For deployment in Docker containers
spring:
  profiles: docker
  # Added to fix -  java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut hystrixCommandAnnotationPointcut
  aop:
    auto: false

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
      fetchRegistry: true
      healthcheck:
        enabled: true 
 
