version: '3'
services:
  restaurant-service:
    image: localhost:5000/dilipwork/restaurantservice:0.0.1-restaurantservice-SNAPSHOT
    ports:
      - "8080:8080"
      
  booking-service:
    image: localhost:5000/dilipwork/booking-service:0.0.1-booking-service-SNAPSHOT
    ports:
      - "8081:8080"    