# For Deployments in docker containers

# Spring properties
spring:
  application:
    name: zuul-server  # Service registers under this name
  messages:
    fallback-to-system-locale: false
  profiles : docker

management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: false
      
zuul:
  ignoredServices: "*"
  routes:
    restaurantapi:
      path: /restaurantapi/**
      serviceId: restaurant-service
      stripPrefix: true   

server:
  port: 8765
  compression:
    enabled: true 

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}}

  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/
    fetchRegistry: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

app:
  ConnectTimeout: 100
  ReadTimeout: 3000



 
    
    

 
