# For Deployments in docker containers

# Spring properties
spring:
  application:
    name: zuul-server  # Service registers under this name
  main:
    allow-bean-definition-overriding: true
  messages:
    fallback-to-system-locale: false
  profiles : docker
  aop:
    auto: false
    
  

management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: false
      
zuul:
  ignoredServices: "*"
  routes:
    restaurantapi:
      path: /restaurantapi/**
      serviceId: restaurant-service
      stripPrefix: true   

server:
  port: 8765
  compression:
    enabled: true 
#Discoveryu Server Access
eureka:
  instance:
    preferIpAddress: true
    ip-address: 192.168.99.100
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
    fetchRegistry: true
    
    
    

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

app:
  ConnectTimeout: 100
  ReadTimeout: 3000



 
    
    

 
